version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:25.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-maven-{{ checksum "pom.xml" }}
            - v2-maven-

      - run:
          name: Resolve dependencies
          command: mvn --batch-mode dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v2-maven-{{ checksum "pom.xml" }}

      - run:
          name: Build and test
          command: mvn --batch-mode --update-snapshots verify

workflows:
  build:
    jobs:
      - build